name: 'Verdaccio Publish Action v2'
description: 'This action will deploy your package to Verdaccio Registry'
author: 'GitHub'
inputs:
  debug:
    description: 'npm debug level'
    default: '-ddd'
  verdaccio-version:
    description: 'Verdaccio version to use'
    default: 'latest'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.debug }}
  env:
    VERDACCIO_VERSION: ${{ inputs.verdaccio-version }}